### ISSUE TITLE
🚀Stable Release Roadmap

### ISSUE THREAD

**Issue by SuspiciousLookingOwl** [SuspiciousLookingOwl/youtubei#12]
As you can see, this library is still in prerelease (`-rc.*`). When I started developing this library, I didn't expect to have this many `rc` versions. 

While I don't have too much time to maintain this library (I will still fix major bugs immediately if exists), I'm still planning to publish a stable release ASAP.

---

### Progress: #53 

---

Some changes and additions to be made before I publish a stable release are:
- [x] Add `Client#getChannel`
- [x] Change `Playlist#next` to `#Playlist#nextVideos`
- [x] Add more params for `Client#search`
- [x] Make `Client#search` accepts continuation token
- [x] Add `Client#getRelatedVideo` (accepts continuation token)
- [x] Add `Client#getComment` (accepts continuation token)
- [x] Add CI/CD for NPM publishing
- [x] Add CI/CD for docs publishing
- [x] Resolve #11
- [x] Some code cleanup (this one is huge, I have internal list of what to refactor)

---

## Migration Guide

List of breaking changes on v1:

1. `ChannelCompact` renamed to `BaseChannel`
2. `Comment#isPinnedComment` renamed to `Comment#isPinned`
3. `Client` constructor parameters changes:
    1. `cookie` renamed to `initialCookie`
    2. `requestOptions` renamed to `fetchOptions` 
    3. `https` removed
4. Remove URL support from `Client#getVideo` and `Client#getPlaylist`, you will have to extract video / playlist id from URL string before passing it
7. `SearchResult` replaced with `SearchManager`, and extending a `Continuable` (look below)
8. `Continuable` implementations. All `.next*()` methods in all classes will be removed (e.g. `Channel#nextVideos`, `Channel#nextPlaylists`, or `Video#nextComments`), and the property used to store fetched data (e.g `Channel.videos`, `Channel.playlists`, or `Video.comments`) will be replaced with a `Continuable`. Instead of doing:
```ts
await channel.nextVideos();
await channel.nextPlaylists();
await video.nextComments();

console.log(channel.videos, channel.playlists, video.comments);
```
on v1:
```ts
await channel.videos.next();
await channel.playlists.next();
await video.comments.next();

console.log(channel.videos.items, channel.playlists.items, video.comments.items);
```
